# Name of your Slack (Deprecated in favour of the SLACK_NAME env var)
slack_name: laterpay
# Name of environmental variable holding a valid Slackbot API token
slackbot_api_token_env_varname: SB_TOKEN
# Name of environmental variable holding a valid general-purpose API token
api_token_env_varname: API_TOKEN
# Days of silence before we warn a channel it's going to be archived
warn_threshold: 30
# Days of silence before we auto-archive a channel
archive_threshold: 60
earliest_archive_date: "2016-03-14"  # Do not archive before this date
# Where should we announce new channels?
announce_channel: "zmeta-new-channels"
# Where do we send control messages?
control_channel: "zmeta-control"
